using Oracle_EFCore.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using Microsoft.EntityFrameworkCore;

namespace Oracle_EFCore
{
    public partial class Form1 : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Oracle_EFCore.Models.ModelContext dbContext = new Oracle_EFCore.Models.ModelContext();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Schools.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                schoolsBindingSource.DataSource = dbContext.Schools.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void btnConnect_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            using (var context = new ModelContext())
            {
                textBox1.Text += $"{Environment.NewLine}연결상태 : {context.Database.CanConnect().ToString()}";
            }
        }

        private async void btnAddData_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            using (var context = new ModelContext())
            {
                var school = new School { Name = "서울고" };
                context.Schools?.Add(school);
                await context.SaveChangesAsync();

                var room1 = new Room { SchoolId = school.Id, Name = "1반" };
                var room2 = new Room { SchoolId = school.Id, Name = "2반" };
                context.Rooms?.Add(room1);
                context.Rooms?.Add(room2);
                await context.SaveChangesAsync();

                var student1 = new Student { RoomId = room1.Id, Name = "홍길동", Age = 267 };
                var student2 = new Student { RoomId = room2.Id, Name = "이연준", Age = 38 };
                var student3 = new Student { RoomId = room2.Id, Name = "윤석열", Age = 59 };
                context.Students?.AddRange(new Student[] { student1, student2, student3 });
                await context.SaveChangesAsync();

                textBox1.Text += $"{Environment.NewLine}저장완료";
            }
        }

        private void schoolsBindingSource_ListChanged(object sender, ListChangedEventArgs e)
        {
            gridControl1.Refresh();
        }
    }
}
